apiVersion: v1
kind: Service
metadata:
  name: serra-nextjs-api
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    app: serra-nextjs-api
  # type: LoadBalancer | ClusterIP | NodePort
  ports:
    - name: http
      port: 3000 # service port
      protocol: TCP
      targetPort: 3000 # container port
